architect:
  - l3r8yJ
docker:
  image: yegor256/rultor-image:latest
assets:
  docker-password: l3r8yJ/home#assets/docker-password
merge:
  script: |-
    sudo docker build "$(pwd)"
release:
  script: |-
    [[ "${tag}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || exit -1
    repo=l3r8y/rust-rultor-image
    sed -i -e "s/^0.0.0/${tag}/" Dockerfile
    sudo docker build "$(pwd)" --tag "${repo}:${tag}"
    cat ../docker-password | sudo docker login --password-stdin --username l3r8y
    sudo docker push "${repo}:${tag}"
